### ISSUE TITLE
Remove typings

### ISSUE THREAD

**Issue by stubailo** [apollostack/subscriptions-transport-ws#13]
Like here: https://github.com/apollostack/angular2-apollo/pull/94

Ping @kamilkisiela, I don't know if it's a lot of work?

Also, CC @lfittl

**Comment by lfittl** [comment]
For added context, I was running into some issues with the `graphql` typings on node v5.X. Looks like switching to node v6.6.0 fixed it.

In case someone else is running into it, these were the errors I ran into on node v5:

```
14         data?: any;
           ~~~~

typings/globals/graphql/index.d.ts(14,9): error TS2300: Duplicate identifier 'data'.


15         errors?: Array<GraphQLError>;
           ~~~~~~

typings/globals/graphql/index.d.ts(15,9): error TS2300: Duplicate identifier 'errors'.


20     class GraphQLError extends Error {
             ~~~~~~~~~~~~

typings/globals/graphql/index.d.ts(20,11): error TS2300: Duplicate identifier 'GraphQLError'.

...
```
