### ISSUE TITLE
Intermittent test/CI fail - Client should throw an error when the susbcription times out

### ISSUE THREAD

**Issue by rricard** [apollostack/subscriptions-transport-ws#18]
```
1) Client should throw an error when the susbcription times out:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
      at Timeout.<anonymous> (/home/travis/build/apollostack/subscriptions-transport-ws/node_modules/mocha/lib/runnable.js:230:19)
      at tryOnTimeout (timers.js:232:11)
      at Timer.listOnTimeout (timers.js:202:5)
```

CI and local tests fail regularly on this specific test. Maybe we're a bit tight in authorised timeout in the tests.

**Comment by helfer** [comment]
That test is basically a race between the (short) timeout and the subscription logic. I think now that we have async onSubscribe, we could fix that test by sleeping for long enough in onSubscribe so the timeout will always be triggered.
