### ISSUE TITLE
I needed to install `babel-preset-es2015` to use this

### ISSUE THREAD

**Issue by tmeasday** [apollostack/subscriptions-transport-ws#23]
I think we just need to remove the `.babelrc` from the published package?

**Comment by stubailo** [comment]
Ah, I think that's a React Native specific issue... let's put the .babelrc in the .npmignore

**Comment by helfer** [comment]
There shouldn't be a babelrc in the first place, since the package uses typescript now. I'll clean it up.

**Comment by helfer** [comment]
@tmeasday should be solved now, can you verify?

**Comment by tmeasday** [comment]
Kind of hard to test without you doing a release (isn't npm fun?), but it looks like it should work.

**Comment by helfer** [comment]
😬

**Comment by tmeasday** [comment]
> 😬
I mean in theory it should be easy for me to take the latest commit from npm into my project and test it, but it totally isn't.

**Comment by helfer** [comment]
Ok, you can try now with 0.2.3!

**Comment by tmeasday** [comment]
all good now!
