### ISSUE TITLE
Handle errors when subscription is active

### ISSUE THREAD

**Issue by helfer** [apollostack/subscriptions-transport-ws#40]
Basically this: https://github.com/apollostack/subscriptions-transport-ws/blob/master/src/server.ts#L153

I just ran into it when updating GitHunt-React.

**Comment by NeoPhi** [comment]
Did https://github.com/apollostack/subscriptions-transport-ws/commit/d6dc6c13cba8177739857645100f0ceca40051dd address this?

**Comment by helfer** [comment]
Yes, I think so...
