### ISSUE TITLE
Other websocket engine/server support

### ISSUE THREAD

**Issue by Maxpain177** [apollostack/subscriptions-transport-ws#44]
In my project i using socket.io with [uws](https://www.npmjs.com/package/uws) engine (it "fastester", because it written with C++), and i using it on csgo.tm, csgo.com, dota2.net, etc. (over  15000 connections at the peak (16 threads CPU, see screenshot below
![screen shot 2016-11-02 at 23 18 37](https://cloud.githubusercontent.com/assets/5875582/19945817/d9d4ac1e-a152-11e6-8d27-6769e2770051.png)

```javascript
import http from 'http'
import socketIO from 'socket.io'

const server = http.Server(app)
const io = socketIO(server, {
	serveClient: false,
	wsEngine: 'uws',
	transports: ['websocket', 'polling']
})
```
How i can connect this engine to the ```subscriptions-transport-ws```?

**Comment by Rusya44** [comment]
+

**Comment by helfer** [comment]
@Maxpain177 WebSockets and socket.io are related but different technologies. If you want to use socket.io, you'd have to build your own transport, which shouldn't be too hard based on the example of this repo.

**Comment by Maxpain177** [comment]
Thanks

**Comment by scf4** [comment]
Max, are you getting worse performance with vanilla websockets in gql subscriptions?

**Comment by Maxpain177** [comment]
@scf4 Yes, but without gql subs. When i using websocket server, writen on pure javascript, cpu usage increases twice.

**Comment by scf4** [comment]
I just found this: https://www.npmjs.com/package/subscriptions-transport-socketio
 
I haven't checked it out and there's no GH repo for it but let me know how it goes!

**Comment by Maxpain177** [comment]
@scf4 It's our package :)

**Comment by DxCx** [comment]
@Maxpain177 please consider adding it to https://github.com/chentsulin/awesome-graphql =)

**Comment by scf4** [comment]
@maxpain177 could you post it on GitHub?

**Comment by Rusya44** [comment]
@scf4 Done.
