### ISSUE TITLE
Why client connect states `graphql-subscriptions` as protocol

### ISSUE THREAD

**Issue by schrepfler** [apollostack/subscriptions-transport-ws#49]
Looking at https://github.com/apollostack/subscriptions-transport-ws/blob/master/src/client.ts#L184
once the connection is opened it immediately set this header `Sec-WebSocket-Protocol:graphql-subscriptions`. Is this strictly needed? I'd imagine there could be different protocols/commands running over a single websocket transport (queries, mutations.. other.)

**Comment by helfer** [comment]
@schrepfler This isn't sent manually, it's part of the websocket implementation that we used and it indicates the subprotocol to the server: https://tools.ietf.org/html/rfc6455#section-1.9

**Comment by schrepfler** [comment]
Thanks, always a pleasure to read IETF's RFCs.
