### ISSUE TITLE
Inconsistency between implementation / README

### ISSUE THREAD

**Issue by timsuchanek** [apollostack/subscriptions-transport-ws#62]
For the `SUBSCRIPTION_FAIL` event, the README says the following:

- `errors: Array<Object>` : array of errors attributed to the subscription failing on the server
- `id: string` : subscription ID of the subscription that failed on the server

So I assume, that the message should look like this:
```js
{
  errors: [...],
  id: '...'
}
```
But the client implementation apparently wants this:
```js
{
  payload: {
    errors: [...],
  },
  id: '...'
}
```
https://github.com/apollostack/subscriptions-transport-ws/blob/master/src/client.ts#L224

So which way do we want to do it? With or without payload?
Because our backend implementation now implements the first version like specified in the README and I'm wondering why `subscriptions-transport-ws` is throwing errors.

**Comment by NeoPhi** [comment]
This is an error in the documentation. All messages from the server should be in the form `{type, id, payload}`. If you want to put together a PR, I'd be happy to review it.
